[advisories]
ignore = []

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "MIT-0",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "Zlib",
  "BSD-3-Clause"
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"
allow = []

[sources]
unknown-registry = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
